version: '3.8'

services:
  postgres:
    image: postgres
    container_name: node_course_postgres_container
    environment:
      POSTGRES_USER: nodejs_course_admin
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: nodejs_course_database
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: node_course_pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_SERVER_PORT: 5432
      PGADMIN_SERVER_NAME: PostgreSQL
    ports:
      - "8080:8080"
    depends_on:
      - postgres